/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cube
 */
public class Overview extends javax.swing.JInternalFrame {

    /**
     * Creates new form Overview
     */
    DefaultTableModel model = new DefaultTableModel();
    ArrayList<Integer> in = new ArrayList<Integer>(); 
    ArrayList<Integer> out = new ArrayList<Integer>(); 
    Integer totalIn = 0, totalOut = 0, totalMoney = 0;
    
    DecimalFormat IndonesiaCurrency = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols RupiahFormat = new DecimalFormatSymbols();
    
    public Overview() {
        initComponents();
        
        RupiahFormat.setCurrencySymbol("Rp ");
        RupiahFormat.setMonetaryDecimalSeparator(',');
        RupiahFormat.setGroupingSeparator('.');

        IndonesiaCurrency.setDecimalFormatSymbols(RupiahFormat);
        
        model = (DefaultTableModel) table.getModel();
        generateData();
        arraySum();
    }

    private void generateData(){
        model.setRowCount(0);
        ResultSet rs = Database.generateInOut();
        try{
            while(rs.next()){
               Object[] data = { rs.getString("id"), rs.getString("account"), rs.getString("type"), rs.getString("category"), IndonesiaCurrency.format(rs.getInt("amount")), rs.getString("transaction_date"), rs.getString("description")};
               model.addRow(data);
               if(rs.getString("type").equals("Income")){
                   in.add(rs.getInt("amount"));
               } else {
                   out.add(rs.getInt("amount"));
               }                   
            }
        } catch(SQLException ex){
            ex.getMessage();
        }
    }
    
    private void arraySum(){
        for(int i=0;i<in.size();i++){
            totalIn += in.get(i);
        }
        for(int i=0;i<out.size();i++){
            totalOut += out.get(i);
        }
        
        totalMoney = totalIn - totalOut;
        
        
        // Display to corresponding textfield
        labelIncome.setText(IndonesiaCurrency.format(totalIn));
        labelOutcome.setText(IndonesiaCurrency.format(totalOut));
        labelCurrMoney.setText(IndonesiaCurrency.format(totalMoney));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        labelIncome = new javax.swing.JLabel();
        labelOutcome = new javax.swing.JLabel();
        labelCurrMoney = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("OVERVIEW");

        jLabel2.setText("INCOME");

        jLabel3.setText("OUTCOME");

        jLabel4.setText("CURRENT MONEY");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Account", "Type", "Category", "Amont", "Date", "Description"
            }
        ));
        jScrollPane1.setViewportView(table);

        labelIncome.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        labelIncome.setText("Rp -");

        labelOutcome.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        labelOutcome.setText("Rp -");

        labelCurrMoney.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        labelCurrMoney.setText("Rp -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCurrMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelIncome))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelOutcome))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelCurrMoney))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurrMoney;
    private javax.swing.JLabel labelIncome;
    private javax.swing.JLabel labelOutcome;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
