/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan4;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cube
 */
public class Tampilan extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan
     */
    int n1, n2, hsl, dsk, ongkir, total_bayar;
    private DefaultTableModel model;
    private JOptionPane error = new JOptionPane();
    
    public Tampilan() {
        initComponents();
        
        model = (DefaultTableModel) table.getModel();
        
        biayaKirim.setEnabled(false);
        biayaKirim.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hargabunga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jumlahbeli = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        struk = new javax.swing.JTextArea();
        cbKirim = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        biayaKirim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jarak1 = new javax.swing.JRadioButton();
        jarak2 = new javax.swing.JRadioButton();
        jarak3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbBunga = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("APLIKASI PENJUALAN BUNGA");

        jLabel2.setText("Nama Bunga");

        jLabel3.setText("Harga/Tangkai");

        jLabel4.setText("Jumlah Beli");

        jLabel5.setText("Diskon");

        jumlahbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahbeliActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("STRUK"));

        struk.setColumns(20);
        struk.setRows(5);
        jScrollPane2.setViewportView(struk);

        cbKirim.setText("Kirim");
        cbKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKirimActionPerformed(evt);
            }
        });

        jLabel6.setText("Biaya Kirim");

        jLabel7.setText("Jarak");

        buttonGroup2.add(jarak1);
        jarak1.setText("< 5 KM");
        jarak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarak1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jarak2);
        jarak2.setText("5 - 15 KM");
        jarak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarak2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jarak3);
        jarak3.setText("> 15 KM");
        jarak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarak3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Total Bayar");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbBunga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Anggrek", "Mawar", "Sedap Malam" }));
        cbBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBungaActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Bunga", "Harga/Tangkai", "Qty", "Diskon", "Ongkir", "Total"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jarak1)
                        .addGap(18, 18, 18)
                        .addComponent(jarak2)
                        .addGap(26, 26, 26)
                        .addComponent(jarak3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(44, 44, 44)
                                        .addComponent(hargabunga))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(67, 67, 67)
                                        .addComponent(jumlahbeli))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(100, 100, 100)
                                        .addComponent(diskon))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbKirim)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(biayaKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(58, 58, 58)
                                        .addComponent(cbBunga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnProses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(hargabunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKirim)
                    .addComponent(jLabel6)
                    .addComponent(biayaKirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jarak1)
                    .addComponent(jarak2)
                    .addComponent(jarak3))
                .addGap(10, 10, 10)
                .addComponent(btnProses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKirimActionPerformed
        // TODO add your handling code here:
        if(cbKirim.isSelected()){
            biayaKirim.setEnabled(true);
            biayaKirim.setText("0");
        } else {
            biayaKirim.setText("0");
            biayaKirim.setEnabled(false);
        }
    }//GEN-LAST:event_cbKirimActionPerformed

    private void jumlahbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahbeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahbeliActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here
        if(cbBunga.getSelectedIndex() == 0){
            error.showMessageDialog(null, "Tidak ada data yang dipilih", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Integer no = 1;
            n1 = Integer.parseInt(hargabunga.getText());
            n2 = Integer.parseInt(jumlahbeli.getText());
            hsl = n1*n2;
            if(hsl > 500000){
                dsk = hsl*10/100;
                diskon.setText(dsk+"");
            } else {
                dsk = 0;
                diskon.setText("0");
            }
            ongkir = Integer.parseInt(biayaKirim.getText());
            total_bayar = hsl - dsk + ongkir;
            int afterDiskon = hsl - dsk;
            total.setText(total_bayar+"");
            String mStruk = "Harga/Tangkai " + "\t\t" + ": " + n1 + "\n"
                    + "Jumlah Beli " + "\t\t" + ": " + n2 + "\n"
                    + "----------------------------- +" + "\n"
                    + "Jumlah " + "\t\t" + ": " + hsl + "\n"
                    + "Diskon " + "\t\t" + ": " + dsk + "\n"
                    + "----------------------------- -" + "\n"
                    + "Jml Stlh Disc " + "\t\t" + ": " + afterDiskon + "\n"
                    + "Ongkir " + "\t\t" + ": " + ongkir + "\n"
                    + "----------------------------- +" + "\n"
                    + "Total Bayar " + "\t\t" + ": " + total_bayar + "\n";
            struk.setText(mStruk);

            Object[] data = {
                no++, cbBunga.getSelectedItem().toString(), n1, n2, dsk, ongkir, total_bayar
            };
            model.addRow(data);
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void jarak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarak1ActionPerformed
        // TODO add your handling code here:
        if(cbKirim.isSelected()){
            biayaKirim.setText("10000");
        } else {
            biayaKirim.setText("0");
        }
    }//GEN-LAST:event_jarak1ActionPerformed

    private void jarak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarak2ActionPerformed
        // TODO add your handling code here:
        if(cbKirim.isSelected()){
            biayaKirim.setText("15000");
        } else {
            biayaKirim.setText("0");
        }
    }//GEN-LAST:event_jarak2ActionPerformed

    private void jarak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarak3ActionPerformed
        // TODO add your handling code here:
        
        if(cbKirim.isSelected()){
            biayaKirim.setText("20000");
        } else {
            biayaKirim.setText("0");
        }
    }//GEN-LAST:event_jarak3ActionPerformed

    private void cbBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBungaActionPerformed
        // TODO add your handling code here:
        if(cbBunga.getSelectedIndex() == 0){
            hargabunga.setText("");
        } else {
            if(cbBunga.getSelectedIndex() == 1){
                hargabunga.setText("5000");
            }
            if(cbBunga.getSelectedIndex() == 2){
                hargabunga.setText("6000");
            }
            if(cbBunga.getSelectedIndex() == 3){
                hargabunga.setText("7000");
            }
        }
    }//GEN-LAST:event_cbBungaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cbBunga.setSelectedIndex(0);
        hargabunga.setText("");
        jumlahbeli.setText("");
        diskon.setText("");
        struk.setText("");
        total.setText("");
        biayaKirim.setText("");
        biayaKirim.setEnabled(false);
        cbKirim.setSelected(false);
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayaKirim;
    private javax.swing.JButton btnProses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbBunga;
    private javax.swing.JCheckBox cbKirim;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField hargabunga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jarak1;
    private javax.swing.JRadioButton jarak2;
    private javax.swing.JRadioButton jarak3;
    private javax.swing.JTextField jumlahbeli;
    private javax.swing.JTextArea struk;
    private javax.swing.JTable table;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
